resolver: lts-18.28
extra-deps:
  - binary-0.8.9.0
  - bytestring-0.11.3.1
  - directory-1.3.7.0
  - hashable-1.4.0.2
  - OneTuple-0.3.1
  - process-1.6.14.0
  - quickcheck-instances-0.3.27
  - rebase-1.15.0.3
  - selective-0.5
  - text-2.0
  - text-short-0.1.5
  - time-compat-1.9.6.1
  - unix-2.7.2.2
