on:
  push:
    branches:
      - master
      - dev

jobs:

  check-formatting:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mrkkrp/ormolu-action@v4

  build:

    strategy:
      matrix:
        ghc: ['8.4', '9.2']
      fail-fast: false

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.4
      
      - run: |
          echo "packages: ." > cabal.project
      - run: cabal update --enable-tests --enable-benchmarks
      - run: cabal freeze --enable-tests --enable-benchmarks

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - run: cabal build --enable-tests --enable-benchmarks
      - run: cabal test --enable-tests --enable-benchmarks --test-show-details=streaming
      
      - if: matrix.ghc != '8.4'
        run: cabal haddock --enable-tests --enable-benchmarks
